### PR TITLE
Add compile-time annotation

### PR DESCRIPTION
**Pull request by gorshkovayulia**

### CODE REVIEW

**Comment by ctapobep** [comment]
I this for AspectJ?

+2

**Comment by gorshkovayulia** [comment]
Yes, but I haven't finished this yet, still in progress of writing Aspect -> for this reason didn't assign this request to you

**Comment by gorshkovayulia** [comment]
@ctapobep not sure that aspect is correct, tests are not failed...how I can see the log message in console?

**Comment by ctapobep** [comment]
We haven't used loggers before, have we? Let's just log it with System.out.println().

**Comment by gorshkovayulia** [comment]
No, _we_ haven’t (I did it myself). But, alas, it looks like idea just ignores my advice(

**Comment by ctapobep** [comment]
Well, you need to add a Maven plugin which will modify classes after they are compiled for this to work.

**Comment by gorshkovayulia** [comment]
> Well, you need to add a Maven plugin which will modify classes after they are compiled for this to work.

Done. I've no idea how to verify this.

**Comment by ctapobep** [comment]
> Done. I've no idea how to verify this.

If you see the message in the console - then it works. You can also decompile the class (either via IDE or using `javap`) and see what's inside.

**Comment by gorshkovayulia** [comment]
> javap

What class are you talking about? (just checking, because current aspect isn't a java class). It doesn't work anyway, I don't see the message in console

**Comment by ctapobep** [comment]
Well, you didn't add the Maven plugin - you only declared its configuration in pluginManagement. That's why it doesn't work. You should be able to see plugin in Maven output if it worked.

**Comment by ctapobep** [comment]
+2

**Comment by gorshkovayulia** [comment]
Will not push this, not sure my code is correct

**Comment by gorshkovayulia** [comment]
>Create an aspect for DogService that adds transactional support. First try Class Proxy and then move to Interface Proxy.

@ctapobep by the way, does this mean that `DogServiceAspect` must contain the same logic as `CglibTransactionalDogService` / `TransactionalProxy` classes or I need to force the use of proxies, e.g. via `<aop:config proxy-target-class="true">` ?

**Comment by ctapobep** [comment]
> or I need to force the use of proxies

AOP uses proxying, so these are not mutually exclusive. Your Aspect needs to have logic similar to what you had in your CGLIB/JdkDynamicProxy implementations.

**Pull request merged**
