### PR TITLE
Add cglib proxy

### PR DESCRIPTION
**Pull request by gorshkovayulia**
Well, now I have a problem with starting of Tomcat: `JdbcConnectionHolder` class also doesn't have default constructor, but how I can pass such parameters to enhancer together with parameters of target class..?

### CODE REVIEW

**Comment by ctapobep** [comment]
Didn't get the question... `JdbcConnectionHolder` is not proxied, why would we worry about its constructors?

**Comment by gorshkovayulia** [comment]
> Didn't get the question... `JdbcConnectionHolder` is not proxied, why would we worry about its constructors?

`Failed to instantiate [com.example.dog.dao.JdbcConnectionHolder]: No default constructor found;` --> do you understand why we need a default constructor for this bean?

**Comment by ctapobep** [comment]
Hm.. no, not from the details that you provided. You need to look at the stack trace as well and see who needs this constructor.

**Comment by gorshkovayulia** [comment]
Fixed by changing the `default-autowire=constructor`

**Comment by ctapobep** [comment]
So why did it help?

**Comment by gorshkovayulia** [comment]
So, from stack trace we see that `DogController` bean cannot be created because `transactionalDogService` and `jdbcConnectionHolder` beans cannot be created. The last bean managed to be created via _autowiring by constructor_ because this way we ask to create bean via calling the constructor _having large number of parameters_ (not via "default" constructor w/o args). And maybe the root case was this fact that type of `dataSource` bean is not the same as we have in `jdbcConnectionHolder` bean...

**Comment by ctapobep** [comment]
Ok, let it be `by constructor` for now. We'll discuss this again on Fri.
+2

**Pull request merged**
